package com.lh.crm.settings.mapper;

import com.lh.crm.settings.domain.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Mar 31 21:24:51 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Mar 31 21:24:51 CST 2023
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Mar 31 21:24:51 CST 2023
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Mar 31 21:24:51 CST 2023
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Mar 31 21:24:51 CST 2023
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Mar 31 21:24:51 CST 2023
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据账户名和密码进行查询
     * @description: 根据账户名和密码进行查询
     * @param: map :账户名:loginAct 密码:loginPwd
     * @return: com.lh.crm.settings.domain.User
     * @author 胡淞纯
     * @date: 2023/4/1 20:22
     */
    User selectUserByPsdAndUserName(Map<String, Object> map);

    List<String> selectAllUserNameList();

}